spring.application.name=GateWay

spring.data.redis.port=6379
spring.data.redis.host=localhost

spring.cloud.gateway.routes[0].id=account-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/account/**
spring.cloud.gateway.routes[0].filters[0].name=RequestRateLimiter
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.replenishRate=10
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.burstCapacity=20

spring.cloud.gateway.routes[1].id=transaction-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/transactions/**
spring.cloud.gateway.routes[1].filters[0].name=RequestRateLimiter
spring.cloud.gateway.routes[1].filters[0].args.redis-rate-limiter.replenishRate=10
spring.cloud.gateway.routes[1].filters[0].args.redis-rate-limiter.burstCapacity=20



# Payment Service
spring.cloud.gateway.routes[2].id=payment-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/payments/**
spring.cloud.gateway.routes[2].filters[0].name=RequestRateLimiter
spring.cloud.gateway.routes[2].filters[0].args.redis-rate-limiter.replenishRate=5
spring.cloud.gateway.routes[2].filters[0].args.redis-rate-limiter.burstCapacity=10




management.endpoints.web.exposure.include=health,info

server.port=8080


